### ISSUE TITLE
Published version is older than sourcecode

### ISSUE THREAD

**Issue by paulbicheler** [heinrichmarkus/delphi-build-plugin#3]
It seems that the version 0.1.7 available in the gradle plugin portal (https://plugins.gradle.org/plugin/de.heinrichmarkus.gradle.delphi) is older than the source-code.
The published plugin 0.1.7 did not work with gradle 5.4.1 but the compiled source-code hosted on the master branch worked. 

Could you please publish the lastest version?

**Comment by heinrichmarkus** [comment]
Published the version 0.1.8 with the latest source-code. The plugin works now with gradle 5.4.1.
